apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: DEPLOY-NAME
  namespace: _namespace_var_
spec:
  selector:
    matchLabels:
      app: DEPLOY-NAME
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: DEPLOY-NAME
    spec:
      containers:
        - name: DEPLOY-NAME
          image: _image_name_var_
          env:
            - name: db_env
              value: _db_env_var_
            - name: docker_env
              value: _docker_env_var_
            - name: run_env
              value: _run_env_var_
---
apiVersion: v1
kind: Service
metadata:
  name: DEPLOY-NAME
  namespace: _namespace_var_
spec:
  type: NodePort
  selector:
    app: DEPLOY-NAME
  ports:
    - protocol: TCP
      port: 80
      nodePort: _external_port_
